name: easy_audio_trimmer
description: A Flutter package for trimming audio. This supports retrieving, trimming, and storage of trimmed audio files to the file system.
version: 1.0.2+4
homepage: https://github.com/mayurpitroda96/easy_audio_trimmer

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.1.0
  ffmpeg_kit_flutter_min_gpl: ^6.0.3
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
